version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.6.1

jobs:
  terraform:
    docker:
    # Terraform image version should be the same as when
    # you run terraform before from the local machine
      - image: hashicorp/terraform:1.0.5
    steps:
      - checkout
     
      - run:
          name: Show Terraform version
          command: terraform version
      - run:
          name: Download required Terraform plugins
          working_directory: terraform
          command: terraform init
      
      - run:
          name: Validate Terraform configuration
          working_directory: terraform
          command: terraform validate
      - run: terraform init 
      - run:
          name: Create Terraform plan
          path: .
          command: terraform plan -out /tmp/tf.plan
      - run:
          name: Run Terraform plan
          path: .
          command: terraform apply /tmp/tf.plan
workflows:
  main:
    jobs:
      - terraform
